### ISSUE TITLE
after a long time mercure is showing an error Unhandled Exception: NoSuchMethodError: The method 'call' was called on null.

### ISSUE THREAD

**Issue by ahmedJD** [herveGuigoz/mercure_client#12]
after a long time of initialisation of mercure client  an error in console appears :
E/flutter (14652): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The method 'call' was called on null.
E/flutter (14652): Receiver: null
E/flutter (14652): Tried calling: call(Instance of 'MercureError')
E/flutter (14652): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter (14652): #1      MercureClient.subscribe (package:mercure_client/src/mercure_client.dart:57:14)
E/flutter (14652): <asynchronous suspension>
E/flutter (14652): #2      MercureClient.subscribe.<anonymous closure> (package:mercure_client/src/mercure_client.dart:48:29)
E/flutter (14652): #3      _rootRun (dart:async/zone.dart:1182:47)
E/flutter (14652): #4      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (14652): #5      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (14652): #6      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:410:13)
E/flutter (14652): #7      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:420:15)
E/flutter (14652): #8      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:305:7)
E/flutter (14652): #9      _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:97:11)
E/flutter (14652): #10     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
E/flutter (14652): #11     _HandlerEventSink.close (dart:async/stream_transformers.dart:255:12)
E/flutter (14652): #12     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:142:24)
E/flutter (14652): #13     _rootRun (dart:async/zone.dart:1182:47)
E/flutter (14652): #14     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (14652): #15     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (14652): #16     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:410:13)
E/flutter (14652): #17     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:420:15)
E/flutter (14652): #18     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:305:7)
E/flutter (14652): #19     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:97:11)
E/flutter (14652): #20     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
E/flutter (14652): #21     _HandlerEventSink.close (dart:async/stream_transformers.dart:255:12)
E/flutter (14652): #22     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:142:24)
E/flutter (14652): #23     _HttpClientResponse.listen.<anonymous closure> (dart:_http/http_impl.dart:443:15)
E/flutter (14652): #24     _rootRun (dart:async/zone.dart:1182:47)
E/flutter (14652): #25     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (14652): #26     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (14652): #27     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:410:13)
E/flutter (14652): #28     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:420:15)
E/flutter (14652): #29     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:305:7)
E/flutter (14652): #30     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:101:10)
E/flutter (14652): #31     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:165:13)
E/flutter (14652): #32     _rootRun (dart:async/zone.dart:1182:47)
E/flutter (14652): #33     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (14652): #34     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (14652): #35     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:410:13)
E/flutter (14652): #36     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:420:15)
E/flutter (14652): #37     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:305:7)
E/flutter (14652): #38     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:816:19)
E/flutter (14652): #39     _StreamController._closeUnchecked (dart:async/stream_controller.dart:671:7)
E/flutter (14652): #40     _StreamController.close (dart:async/stream_controller.dart:664:5)
E/flutter (14652): #41     _HttpParser._closeIncoming (dart:_http/http_parser.dart:1129:18)
E/flutter (14652): #42     _HttpParser._doParse (dart:_http/http_parser.dart:793:11)
E/flutter (14652): #43     _HttpParser._parse (dart:_http/http_parser.dart:324:7)
E/flutter (14652): #44     _HttpParser._onData (dart:_http/http_parser.dart:853:5)
E/flutter (14652): #45     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (14652): #46     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (14652): #47     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (14652): #48     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter (14652): #49     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
E/flutter (14652): #50     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
E/flutter (14652): #51     _S

**Comment by herveGuigoz** [comment]
Thank you for the report! Issue was fixed in version 1.0.0.
