### ISSUE TITLE
Does not work for me in browser

### ISSUE THREAD

**Issue by zim32** [herveGuigoz/mercure_client#17]
I got strange behavior when using this package in browser (Chrome)

Most of the time I did not receive updates. 
In Caddy logs I can see that update was sent:

`"level":"info","ts":1651780975.8573892,"logger":"http.handlers.mercure","msg":"Update sent","subscriber":{"id":"urn:uuid:02884db6-cc00-4089-a1b6-33e1402bc203","last_event_id":"","remote_addr":"172.29.0.1:36122","topics":["/role/ROLE_WAITER","/role/ROLE_USER"]},"update":{"id":"urn:uuid:027d189b-2bf7-4a8e-866e-3f737e66b01d","type":"","retry":0,"topics":["/role/ROLE_WAITER","/user/at781hfea2gh62f83c7ee1452e"],"private":false}}
`

But once after some random reloads and restarts I was able to receive one update in browser. But then it breaks again.

I was testing in Chrome, in release and debug builds. Same thing.

**Comment by zim32** [comment]
It seems like this package does not support web right now.
I can help. I will add web support by using native javascript EventSource.
There will be conditional import for web.
I've tested it, and it works great. 

One thing to note is MercureEvent::id field is not available in javascript code. So it will be empty string in web

**Comment by herveGuigoz** [comment]
Your right and conditional imports for J's event source  is missing on this package. thank you for contributing
